name: Mlflow CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-mlflow-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Micromamba
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: MLproject/conda.yaml
          cache-environment: true

      # Verify environment
      - name: Verify environment
        run: |
          micromamba run -n mlflow-env python --version
          micromamba run -n mlflow-env mlflow --version

      # Run MLflow project
      - name: Run MLflow project
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          micromamba run -n mlflow-env \
            mlflow run MLproject \
              -P dataset=train_preprocessing.csv \
              -P n_iter=10 \
              -P cv=3

      # Upload MLflow artifacts
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns
